# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a25fdf12b1b10b970465ebbe0a79bab53c9cf62d6fa4f8febc7f1214adb18abe52904378cb8d7eac1aec0bc27a6cbf05074e9ce30018dd647b1df62d0259c1be

test:
  secret_key_base: f286c4ec34f62fe8e5ddf9d1463a6234661f7d6911912d55c2bb7dd9b9017677b1722a1b9eb80b0849dfb48eff34c16e0695868cbec8bdee88cc13cfa0550e2c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
